export const LOAD_STAFF_MEMBERS_STARTUP = 'LOAD_STAFF_MEMBERS_STARTUP';
export const LOAD_STAFF_MEMBERS_SUCCESS = 'LOAD_STAFF_MEMBERS_SUCCESS';
export const LOAD_STAFF_MEMBERS_FAILURE = 'LOAD_STAFF_MEMBERS_FAILURE';

export const LOAD_STAFF_MEMBER_STARTUP = 'LOAD_STAFF_MEMBER_STARTUP';
export const LOAD_STAFF_MEMBER_SUCCESS = 'LOAD_STAFF_MEMBER_SUCCESS';
export const LOAD_STAFF_MEMBER_FAILURE = 'LOAD_STAFF_MEMBER_FAILURE';
